version: '3.7'
services:
  mongo:
    image: mongo:6
    container_name: churn_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo_data:/data/db

  airflow:
    image: apache/airflow:2.8.0
    container_name: churn_airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/airflow.db:/opt/airflow/airflow.db
    ports:
      - "8080:8080"
    command: webserver

  n8n:
    image: n8nio/n8n:latest
    container_name: churn_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_DATABASE_TYPE=mongodb
      - N8N_DATABASE_MONGODB_CONNECTION_URL=mongodb://admin:changeme@mongo:27017/churndb
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
    depends_on:
      - mongo
    volumes:
      - ./data:/data

volumes:
  mongo_data:
